/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum DisplayStyle {
  Block = 'Block',
  Inline = 'Inline'
}

export declare function latexToAst(latex: string): string

export declare function latexToMathml(latex: string, display: DisplayStyle): string
